### ISSUE TITLE
Probleme lors du premier pont du premier level

### ISSUE THREAD

**Issue by Yamzho** [Afendar/StoryIntoJungle#4]
![sij2](https://cloud.githubusercontent.com/assets/11474023/16173669/2add2f48-35a9-11e6-9f39-65e164f9810b.png)

Il est impossible pour le joueur de passer le premier pont du premier level (en ce qui me concerne en tous cas). Les "briques" du pont disparaissent trop rapidement pour pouvoir le passer, que ce soit en sautant ou en marchant sans sauter dessus.

**Comment by Afendar** [comment]
Il faut appuyer sur ctrl car le panda court et donc le pont se brise sous les vibrations.
